"""Pack a whole profile into one file, and unpack it again.

A profile is only partly rows in the database. The rest of it — cookies, local
storage, history, saved logins — lives in a Firefox profile directory, and an
account that has been warmed up for months is mostly that directory. Exporting
the settings alone would move the costume without the memory.

So an archive carries both: the profile record (including the pinned
fingerprint) and the browser data directory. Restoring it elsewhere gives back a
profile that is the same machine *and* still logged in.

Layout of the archive::

    manifest.json   format version and what produced it
    profile.json    the profile record
    data/…          the browser profile directory

The archive is not encrypted. It contains session cookies and the proxy
password, so it is exactly as sensitive as the account it belongs to.
"""

import json
import shutil
import zipfile
from pathlib import Path
from typing import Any

from loguru import logger

from camoufox_pm import __version__
from camoufox_pm.core.models import Profile

FORMAT_VERSION = 1
MANIFEST_NAME = "manifest.json"
PROFILE_NAME = "profile.json"
DATA_PREFIX = "data/"

# Regenerated by the browser on demand, and by far the bulk of the directory —
# a profile is ~50 MB of which ~30 MB is startupCache alone. Excluding these
# costs nothing and keeps archives small enough to move around.
_DISPOSABLE = frozenset(
    {
        "cache2",
        "startupCache",
        "shader-cache",
        "thumbnails",
        "crashes",
        "minidumps",
        "datareporting",
        "saved-telemetry-pings",
        "security_state",
        "sessionstore-backups",
        "lock",
        ".parentlock",
    }
)


def _should_skip(relative: Path) -> bool:
    """Skip disposable caches and the lock files of a running browser."""
    return any(part in _DISPOSABLE for part in relative.parts)


def export_profile(profile: Profile, data_dir: Path, destination: Path) -> Path:
    """Write ``profile`` and its browser data into a zip at ``destination``."""
    manifest = {
        "format_version": FORMAT_VERSION,
        "produced_by": f"camoufox-pm {__version__}",
        "profile_id": profile.id,
        "profile_name": profile.name,
    }
    record = profile.model_dump(mode="json")
    # The id and the on-disk path belong to the instance that exported it; an
    # import assigns its own.
    record.pop("id", None)
    record.pop("storage_path", None)

    written = 0
    with zipfile.ZipFile(destination, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        archive.writestr(MANIFEST_NAME, json.dumps(manifest, indent=2))
        archive.writestr(PROFILE_NAME, json.dumps(record, indent=2))

        if data_dir.is_dir():
            for path in sorted(data_dir.rglob("*")):
                if not path.is_file():
                    continue
                relative = path.relative_to(data_dir)
                if _should_skip(relative):
                    continue
                try:
                    archive.write(path, DATA_PREFIX + relative.as_posix())
                    written += 1
                except OSError as exc:  # a file vanished or is locked
                    logger.warning(f"Skipped {relative} while exporting: {exc}")

    logger.info(f"Exported profile {profile.id} with {written} data files")
    return destination


def read_archive(source: Path) -> dict[str, Any]:
    """Return the profile record from an archive, validating its shape."""
    with zipfile.ZipFile(source) as archive:
        names = set(archive.namelist())
        if MANIFEST_NAME not in names or PROFILE_NAME not in names:
            raise ValueError("Not a Camoufox profile archive")

        manifest = json.loads(archive.read(MANIFEST_NAME))
        version = manifest.get("format_version")
        if version != FORMAT_VERSION:
            raise ValueError(
                f"Unsupported archive format {version}; this build reads version {FORMAT_VERSION}"
            )
        return json.loads(archive.read(PROFILE_NAME))


def extract_data(source: Path, target_dir: Path) -> int:
    """Restore the browser data directory from an archive.

    Entries are placed by resolved path and anything landing outside the target
    is refused, so a crafted archive cannot write elsewhere on the machine.
    """
    target_dir.mkdir(parents=True, exist_ok=True)
    resolved_target = target_dir.resolve()
    restored = 0

    with zipfile.ZipFile(source) as archive:
        for name in archive.namelist():
            if not name.startswith(DATA_PREFIX) or name.endswith("/"):
                continue
            relative = name[len(DATA_PREFIX) :]
            destination = (target_dir / relative).resolve()
            if not destination.is_relative_to(resolved_target):
                logger.warning(f"Refused archive entry outside the profile: {name}")
                continue
            destination.parent.mkdir(parents=True, exist_ok=True)
            with archive.open(name) as member, open(destination, "wb") as handle:
                shutil.copyfileobj(member, handle)
            restored += 1

    logger.info(f"Restored {restored} data files into {target_dir}")
    return restored
