"""Packing a profile into one file and getting it back."""

import json
import zipfile

import pytest

from camoufox_pm.core import profile_archive
from camoufox_pm.core.models import BrowserSettings, Profile, ProxyConfig, ProxyType


def build_profile() -> Profile:
    return Profile(
        name="warmed-up",
        notes="months of history",
        browser_settings=BrowserSettings(os="windows", timezone="Europe/Berlin"),
        proxy=ProxyConfig(type=ProxyType.HTTP, server="1.2.3.4:8080", password="secret"),
        fingerprint={"navigator.userAgent": "UA", "screen.width": 1920},
    )


def build_data_dir(root):
    """A directory shaped like a Firefox profile, with junk worth skipping."""
    data = root / "browser-data"
    (data / "storage" / "default").mkdir(parents=True)
    (data / "startupCache").mkdir(parents=True)
    (data / "cache2" / "entries").mkdir(parents=True)

    (data / "cookies.sqlite").write_bytes(b"COOKIES")
    (data / "prefs.js").write_text('user_pref("x", 1);')
    (data / "storage" / "default" / "ls.data").write_bytes(b"LOCALSTORAGE")
    (data / "startupCache" / "big.bin").write_bytes(b"x" * 5000)
    (data / "cache2" / "entries" / "blob").write_bytes(b"y" * 5000)
    return data


def test_export_carries_the_browser_data_but_not_the_caches(tmp_path):
    archive_path = tmp_path / "out.zip"
    profile_archive.export_profile(build_profile(), build_data_dir(tmp_path), archive_path)

    with zipfile.ZipFile(archive_path) as archive:
        names = archive.namelist()

    assert "manifest.json" in names
    assert "profile.json" in names
    assert "data/cookies.sqlite" in names
    assert "data/prefs.js" in names
    assert "data/storage/default/ls.data" in names
    # Regenerated by the browser and by far the bulk of a real profile.
    assert not any(name.startswith("data/startupCache") for name in names)
    assert not any(name.startswith("data/cache2") for name in names)


def test_the_record_travels_without_instance_specific_fields(tmp_path):
    archive_path = tmp_path / "out.zip"
    profile_archive.export_profile(build_profile(), build_data_dir(tmp_path), archive_path)

    record = profile_archive.read_archive(archive_path)
    assert record["name"] == "warmed-up"
    assert record["fingerprint"]["navigator.userAgent"] == "UA"
    assert record["browser_settings"]["timezone"] == "Europe/Berlin"
    # The importing instance assigns these itself.
    assert "id" not in record
    assert "storage_path" not in record


def test_round_trip_restores_the_files(tmp_path):
    archive_path = tmp_path / "out.zip"
    profile_archive.export_profile(build_profile(), build_data_dir(tmp_path), archive_path)

    restored = tmp_path / "restored"
    count = profile_archive.extract_data(archive_path, restored)

    assert count == 3
    assert (restored / "cookies.sqlite").read_bytes() == b"COOKIES"
    assert (restored / "storage" / "default" / "ls.data").read_bytes() == b"LOCALSTORAGE"


def test_a_foreign_zip_is_refused(tmp_path):
    stranger = tmp_path / "stranger.zip"
    with zipfile.ZipFile(stranger, "w") as archive:
        archive.writestr("hello.txt", "not a profile")

    with pytest.raises(ValueError, match="Not a Camoufox profile archive"):
        profile_archive.read_archive(stranger)


def test_a_future_format_is_refused(tmp_path):
    future = tmp_path / "future.zip"
    with zipfile.ZipFile(future, "w") as archive:
        archive.writestr("manifest.json", json.dumps({"format_version": 99}))
        archive.writestr("profile.json", json.dumps({"name": "x"}))

    with pytest.raises(ValueError, match="Unsupported archive format"):
        profile_archive.read_archive(future)


def test_entries_cannot_escape_the_profile_directory(tmp_path):
    """A crafted archive must not be able to write outside the target."""
    malicious = tmp_path / "evil.zip"
    with zipfile.ZipFile(malicious, "w") as archive:
        archive.writestr("manifest.json", json.dumps({"format_version": 1}))
        archive.writestr("profile.json", json.dumps({"name": "evil"}))
        archive.writestr("data/../../escaped.txt", "pwned")
        archive.writestr("data/legit.txt", "fine")

    target = tmp_path / "target"
    restored = profile_archive.extract_data(malicious, target)

    assert restored == 1
    assert (target / "legit.txt").exists()
    assert not (tmp_path.parent / "escaped.txt").exists()
    assert not (tmp_path / "escaped.txt").exists()


def test_extract_refuses_an_oversized_archive(tmp_path, monkeypatch):
    """A decompression bomb must not be allowed to fill the disk."""
    monkeypatch.setattr(profile_archive, "_MAX_EXTRACTED_BYTES", 1000)

    bomb = tmp_path / "bomb.zip"
    with zipfile.ZipFile(bomb, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("manifest.json", json.dumps({"format_version": 1}))
        archive.writestr("profile.json", json.dumps({"name": "bomb"}))
        # Highly compressible, so the archive stays tiny while the payload is huge.
        archive.writestr("data/huge.bin", b"\0" * 10_000)

    with pytest.raises(ValueError, match="larger than the import limit"):
        profile_archive.extract_data(bomb, tmp_path / "target")


def test_export_survives_a_missing_data_directory(tmp_path):
    """A profile that has never been launched has no directory yet."""
    archive_path = tmp_path / "out.zip"
    profile_archive.export_profile(build_profile(), tmp_path / "nothing-here", archive_path)

    record = profile_archive.read_archive(archive_path)
    assert record["name"] == "warmed-up"
